name: zip
on:
  push:
    branches:
      - main

env:
  VERSION: 0.2.0
  MINECRAFT_VERSION: 1.21.11
  NOTES: |
    - Added SMP
    - Renamed zip files
    - Added custom model data example

jobs:
  zip-and-publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: ü´∏Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: 'v${{ env.VERSION }}_${{ env.MINECRAFT_VERSION }}'
            release_name: '${{ github.event.repository.name }} v${{ env.VERSION }} ${{ env.MINECRAFT_VERSION }}'
            body: '${{ env.NOTES }}'

      - name: ü§ê Zipping SMP
        uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: SMP/
          dest: SMP.zip

      - name: ü§ê Zipping Hub
        uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: Hub/
          dest: Hub.zip

      - name: ‚¨ÜÔ∏è Uploading SMP Release
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
            asset_path: ./SMP.zip
            asset_name: SMP.zip
            asset_content_type: application/zip

      - name: ‚¨ÜÔ∏è Uploading Hub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./Hub.zip
          asset_name: Hub.zip
          asset_content_type: application/zip

      - name: ‚úÖ Publishing release
        run: gh release edit project --draft=false
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
